apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: namespacelab9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate   #type
    rollingUpdate: # définition
      maxSurge: 2  # nb de pods sup. autorisés
      maxUnavailable: 0 # nb de pod supprimés pour la monté de version

  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: acrlab009.azurecr.io/api/api:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000